# ProxyDHCP — NovaSCM iPXE (backup se DHCP option 66/67 non configurabile sul gateway)
# IP server NovaSCM: 192.168.20.110 (CT 103)
port=0
dhcp-range=192.168.10.0,proxy
log-dhcp
pxe-service=X86-64_EFI,"NovaSCM PXE Boot (UEFI)",ipxe.efi,192.168.20.110
pxe-service=BC_EFI,"NovaSCM PXE Boot (EFI-BC)",ipxe.efi,192.168.20.110
